name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Node versions list
      matrix:
        node-version: [16.x]
    steps:
      - name: npm install
        run: | 
          make install
          make lint
